# 数据操作

### 导入pytorch

In [1]:
import torch

### 张量表示一个由数值组成的数组，这个数字可能有多个维度

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# shape属性访问张量的形状和张量中元素的总数
x.shape

torch.Size([12])

In [6]:
x.numel()  # 标量，元素总数

12

In [8]:
# reshape 改变张量的形状
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
# 全0、全1、其他常量的张量
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
# 赋值张量
torch.tensor([[2,1,4,5], [1,2,3,4], [3,2,5,1], [4,3,2,1]])

tensor([[2, 1, 4, 5],
        [1, 2, 3, 4],
        [3, 2, 5, 1],
        [4, 3, 2, 1]])

常见的标准算术运算符（+、-、*、/和**）都会升级为按元素运算