池化层的正向传播

In [1]:
import torch
from torch import nn
from d2l import torch as d2l

def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i:i + p_h, j:j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i:i + p_h, j:j + p_w].mean()
    return Y

填充和步幅

In [3]:
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))

In [4]:
# 深度学习框架中的步幅与池化窗口的大小相同
pool2d = nn.MaxPool2d(3)  # 3代表是一个3x3的窗口
pool2d(X)

tensor([[[[10.]]]])

In [5]:
# 填充和步幅可以手动设定
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)  

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [6]:
# 可以设定任意大小的矩形池化窗口，并分别设定填充和步幅的高度和宽度
pool2d = nn.MaxPool2d((2, 3), padding=(1, 1), stride=(2, 3))

In [7]:
X = torch.cat((X, X + 1), 1)

In [8]:
# 池化层在每个输入通道上单独运算
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])