# 线性代数

创建 m x n 的矩阵

In [2]:
import torch
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置  行变列，列变行

In [3]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵：A等于其转置  A = AT

In [4]:
B = torch.tensor([[1,2,3], [2,0,4], [3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [5]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

使用reshape构建更多轴的数据结构

In [7]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

指定求和汇总张量的轴

In [ ]:
A = torch.arange(20*2).reshape(2, 5, 4)
A_sum_axis0 = A.sum(axis=0)  
A_sum_axis0, A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [9]:
A.sum(axis=[0, 1]).shape

torch.Size([4])

求平均值

In [12]:
A.float().mean()

tensor(19.5000)

In [13]:
A.float().mean(axis=0)

tensor([[10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.],
        [26., 27., 28., 29.]])

某个轴计算A元素的累计总和

In [14]:
A.cumsum(axis=0)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]])

点积是相同位置的按元素乘积的和

In [16]:
x = torch.tensor([0, 1, 2, 3]).float()
y = torch.ones(4, dtype=torch.float32)

x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

也可以通过执行元素乘法，再求和来表示两个向量的点积

In [17]:
torch.sum(x * y)

tensor(6.)

In [ ]:
A = torch.arange(20).reshape(5, 4).float()
A.shape, x.shape, torch.mv(A, x)   # 矩阵乘向量

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [23]:
B = torch.ones(4, 3)
torch.mm(A, B)   # 矩阵乘矩阵

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

L2范数：向量元素平方和的平方根

In [24]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

L1范数：表示为向量元素的绝对值之和

In [25]:
torch.abs(u).sum()

tensor(7.)

矩阵的 弗罗贝尼乌斯范数 矩阵元素的平方和的平方根

In [26]:
torch.norm(torch.ones((4,9)))

tensor(6.)

In [28]:
a = torch.ones((2, 5, 4))
a.shape

torch.Size([2, 5, 4])

In [29]:
a.sum(axis=1).shape

torch.Size([2, 4])

In [31]:
a.sum(axis=[0,2])

tensor([8., 8., 8., 8., 8.])

In [32]:
a.sum(axis=[0, 2], keepdim=True)

tensor([[[8.],
         [8.],
         [8.],
         [8.],
         [8.]]])