# 自动求导

In [11]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [12]:
x.requires_grad_(True)  # 告诉pytorch要计算x的梯度，让其记录凡是x参与的计算
x.grad  # 存储X的梯度

In [13]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

通过调用反向传播函数来自动计算y关于X每个分量的梯度    

In [14]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [15]:
x.grad == 4 * x

tensor([True, True, True, True])

In [17]:
# 在默认情况下，pytorch会累计梯度，需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

将某些计算移动到记录的计算图之外 

In [ ]:
x.grad.zero_()
y = x * x
u = y.detach()  # 把 y 从计算图里摘出来，返回一个值和 y 完全一样但没有梯度信息的 tensor，把y当常数用
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [ ]:
# PyTorch 自动求导可以穿过 Python 控制流（while 循环、if-else）

def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

a.grad == d / a

tensor(102400.)